services:
  webapp:
    build: .
    container_name: webapp
    ports:
      - "80:5000"
    volumes:
      - .:/app
    working_dir: /app
  
  mysqldb:
    image: mysql:8.0
    container_name: mysqldb
    restart: always
    volumes:
      - ./mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: gitea
      MYSQL_USER: gitea
      MYSQL_PASSWORD: pass

  gitserver:
    image: alpine:latest
    container_name: gitserver
    ports:
      - "9418:9418"
    volumes:
      - ./git_repos:/git
    command: >
      sh -c "apk add --no-cache git git-daemon &&
             git config --global user.name 'Muhammad Hanif Bin Shaiful Bhari' &&
             git config --global user.email '2301872@sit.singaporetech.edu.sg' &&
             mkdir -p /git &&
             git daemon --reuseaddr --base-path=/git --export-all --verbose --enable=receive-pack"